remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jemoji
title: [Thereache]
description: [A custom rom By Thereache]
relative_links:
  enabled: true
  collections: true
include:
  - download.html
  - troubleshooting.html
  - about_me.html
